apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: webapp-nodejs
      image: public.ecr.aws/t7d7t4m1/webapp-nodejs-repo:latest
      ports:
        - containerPort: 3000
  restartPolicy: Always
