apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: webapp-nodejs
      image: ngnix
      ports:
        - containerPort: 8080
  restartPolicy: Always
