---
- name: Install Apache
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update-cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present
